version: "3.9"

services:
  db:
    image: postgres:16
    container_name: cargo_app_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cargo_app
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # api:
  #   build: .
  #   container_name: cargo_app_api
  #   restart: always
  #   ports:
  #     - "8000:8000"
  #   environment:
  #     DATABASE_URL: postgresql://postgres:postgres@db:5432/cargo_app
  #   depends_on:
  #     - db
  #   volumes:
  #     - .:/app

volumes:
  postgres_data:
